### ISSUE TITLE
Atualizar versão do Node no projeto

### ISSUE THREAD

**Issue by ayrtonteshima** [programadorabordo/ead-api#11]
A imagem Docker do Node está na versão `10.5.3`. Precisamos fazer o upgrade dessa imagem para a versão mais recente.
Atualmente a versão mais recente é `14.3.0` e a stable `12.16.3`.
Utilizar a 14 é interessante pois já disponibiliza os novos recursos do ES2020

**Comment by TonyALS** [comment]
Também concordo com a atualização. Mas não seria melhor manter na versão LTS? Como é focado para iniciantes seria uma boa para evitar possíveis problemas (bugs).

**Comment by joaohenrique-hs** [comment]
A 14 vira LTS em Outubro.
Uma vantagem da versão 14 é poder usar ES modules, que usa a sintaxe de `import` ao invés de `require`, sem a necessidade de utilizar um transpilador.
Isso ajuda na compatibilidade com o Deno, que já usa ESM também.

**Comment by TonyALS** [comment]
@joaohenrique-hs não sabia que a 14 já viraria LTS ainda esse ano. Então concordo com a mudança, realmente a sintaxe import/export sem uso de sucrase é uma ótima. Como está tão perto de transformar a 14 em LTS provavelmente não teremos grandes mudanças até lá.

**Comment by programadorabordo** [comment]
Boaa @TonyALS @joaohenrique-hs ! Acho difícil a gente também pegar algum bug. Sem contar que, ainda estamos desenvolvendo a API. Quando ela for para produção, muito provável que a 14 já seja a stable!

**Comment by xavierleonardo** [comment]
Não sou contra a atualização, mas creio que, como não é um projeto exclusivamente para o estudo, mas também para o uso externo, creio que seja mais seguro e prudente se manter na versão LTS, embora o bom histórico de poucos bugs do Node. Além disso, não é preciso versão 14 para o uso do `import`/`export`, vide este exemplo bem simplista que está usando apenas com TS: /xavierleonardo/gostack9-challenge1/tree/feature/posts
