### ISSUE TITLE
Quais funcionalidades um EAD tem?

### ISSUE THREAD

**Issue by ayrtonteshima** [programadorabordo/ead-api#2]
E aí pessoal, vamos fazer um brainstorm de ideias que um EAD precisa/pode ter e no fim definir o que vamos atacar primeiro?

O ideal é começarmos pelo "coração" da aplicação, as principais funcionalidades e futuramente ir atacando os extras.

Porém, vamos sem restrição e listar todas as funcionalidades possíveis, ok?

### Algumas sugestões
- Padrão SCORM
- Catálogo de cursos
- Aulas com diferentes mídias (vídeo, pdf, imagem, texto, etc.)
- Gamificação
- Ranking
- Provas
- Exercício online/interativo
- Certificação
- Chat
- Área de dúvidas
- Aula online
- Sala de aula
- Assinaturas
  - Plano mensal/semestral/anual
  - Curso único
- Cupom de desconto

**Comment by jqueryalmeida** [comment]
- Aulas com diferentes mídias (vídeo, pdf, imagem, texto, **quiz** etc.)

**Comment by vallef** [comment]
Ser um portal multidiomas. Eu me prontifico a cuidar da tradução para a língua internacional Esperanto. Sou presidente da ONG Língua Social, que adota o Esperanto como língua de trabalho. Se o portal funcionar direitinho e for competitivo, posso convocar esperantistas de todo o mundo para ajudar na tradução do Esperanto para diversas outras línguas. O Esperanto tem comunidade de falantes em mais de 100 países.

**Comment by vallef** [comment]
Compartilhamento nativo de conteúdo promocional para as principais redes sociais. Por exemplo, comparilhar ementas dos cursos

**Comment by vallef** [comment]
Rede social interna, que permita interação entre  alunos/alunos e alunos/monitores, formação de grupos

**Comment by vallef** [comment]
API para integração com meios de pagamento, inclusive pagamentos internacionais

**Comment by vallef** [comment]
Parece que já existe algo mais avanançado que padrão SCORM. Vamos dar uma verificada nisso

**Comment by Militao36** [comment]
@ayrtonteshima  Muito bacana, todas sugestões. Estou ansioso para ajudar no projeto =D

**Comment by evertonthepaula** [comment]
Modulo de pagamento.

Na minha singela opinião deve ser pensado como algo a parte, uma API onde você pode plugar um modulo próprio, ou uma interface de pagamento como a da https://pagar.me/ .

**Comment by ayrtonteshima** [comment]
@peduardo1 Legal! Mas acho que isso dá pra ser um sistema separado... Já vi plataformas utilizar o sistema de ticket e report de erro em outros sistemas só com essa responsabilidade

**Comment by ayrtonteshima** [comment]
Fala @peduardo1, maneiro!! Mas eu acho que isso pode ser um sistema a parte, só com essa responsabilidade de reportar erros, pelo menos é o que costumo ver..

**Comment by ayrtonteshima** [comment]
> Modulo de pagamento.
> 
> Na minha singela opinião deve ser pensado como algo a parte, uma API onde você pode plugar um modulo próprio, ou uma interface de pagamento como a da https://pagar.me/ .

A ideia é que seja desacoplado de qualquer serviço de pagamento, bastando adicionar um módulo para integrar, sendo de fácil integração :)

**Comment by vallef** [comment]
> Galera, só lembrando uma coisa: a visão que tenho dessa plataforma é ela ser como um serviço de EAD, onde qualquer layout pode se integrar a ela como uma API RESTFul, então ela tem que ser bem flexível nas questões. Uma referência que tenho de API bem maneira mas que é pago, é essa: https://api.eadbox.com

> Depois de ver a necessidade de comprar e preço, poderemos fazer uma vaquinha. Parece que vai adiantar muita coisa. Sugiro abrir issue só para avaliar essa API, mostrando o papel dela no projeto etc.

**Comment by PereiraJesse** [comment]
Na questão do certificado, seria interessante gerar um link para que pudesse ser adicionado diretamente ao linkedin  ou o certificado digital supre essa necessidade?

**Comment by nelsonmfinda** [comment]
Quanto ao ***cupom de desconto***, seria legal poder gerar um _link de indicação(Referral link)_ com desconto de X% para cada usuário(Ou até um certo número de usuários) que comprar ou se inscrever no curso.

**Comment by ayrtonteshima** [comment]
> Modulo de pagamento.
> 
> Na minha singela opinião deve ser pensado como algo a parte, uma API onde você pode plugar um modulo próprio, ou uma interface de pagamento como a da https://pagar.me/ .

Seria TOP se o @filipedeschamps fizesse esse módulo de pagamento do pagarme para a plataforma. Fica a dica ;)

**Comment by ayrtonteshima** [comment]
> > Galera, só lembrando uma coisa: a visão que tenho dessa plataforma é ela ser como um serviço de EAD, onde qualquer layout pode se integrar a ela como uma API RESTFul, então ela tem que ser bem flexível nas questões. Uma referência que tenho de API bem maneira mas que é pago, é essa: https://api.eadbox.com
> 
> > Depois de ver a necessidade de comprar e preço, poderemos fazer uma vaquinha. Parece que vai adiantar muita coisa. Sugiro abrir issue só para avaliar essa API, mostrando o papel dela no projeto etc.

Não consegui entender, pode explicar?

**Comment by raphaeljq** [comment]
Seria legal ter uma rede social interna também.

**Comment by bogacha** [comment]
Sendo aluno de algumas plataformas desse tipo sinto a necessidade de sair da mesma para buscar uma sequencia após terminado um curso, seria legal se a plataforma me desse uma sugestão de qual seria o meu próximo passo.
Por exemplo fiz o curso de HTML a plataforma me sugere CSS, depois JS e assim por diante.

**Comment by pweslly** [comment]
Comentários  por aula do curso e não do curso todo.

TIpo curso:   Primeiros Passos com REACT native

Aula 01:  Introdução
Aula 02: Instalando o node.js
Aula03: Instalando React-Native


Quando alguém for comentar ela poder filtrar por aula.
Se eu fizer comentários na Aula 01: Introdução , **o meu comentário vai ficar só nessa aula** e sucessivamente ou então adicionar também ver **todos comentários** ou **comentários por aula.**
