### ISSUE TITLE
Quais tecnologias serão utilizadas no desenvolvimento da plataforma EAD?

### ISSUE THREAD

**Issue by nelsonmfinda** [programadorabordo/ead-api#3]
Pelo que entendi, depois de ver o primeiro vídeo :nerd_face: essa questão ainda está meio que indecisa certo? Seria legal, depois de fechar essa https://github.com/programadorabordo/ead-api/issues/2 issue debatermos sobre quais tecnologias(Frontend, Backend, Infra, e etc...) serão utilizadas.

**Comment by ayrtonteshima** [comment]
Fala Nelson, tem algumas coisas definidas já. 

A linguagem vai ser JavaScript/Node. 
O admin vai ser em React (framework js).
O que ficou aberto é o melhor tipo de banco de dados (relacional, não relacional, etc.)

**Comment by ayrtonteshima** [comment]
Eu falo isso nesse vídeo aqui hehe https://youtu.be/WqgAi3ymajY

**Comment by Militao36** [comment]
Acredito que banco não relacional seria uma boa para o projeto

**Comment by edutav** [comment]
acredito que dependendo da tomada que o projeto tomar podemos usar tanto banco sql quanto nosql

**Comment by nelsonmfinda** [comment]
Podemos aproveitar o melhor dos dois mundos :100: para notificações, chat e tal podemos usar _nosql_, e para informações gerencias o _sql_. O que acha @ayrtonteshima?

**Comment by nelsonmfinda** [comment]
> Fala Nelson, tem algumas coisas definidas já.
> 
> A linguagem vai ser JavaScript/Node.
> 
> O admin vai ser em React (framework js).
> 
> O que ficou aberto é o melhor tipo de banco de dados (relacional, não relacional, etc.)

Opah! DHR hem, assim aproveito e dou um up nas minhas skills em _NodeJS_ :1st_place_medal:

**Comment by ayrtonteshima** [comment]
> Podemos aproveitar o melhor dos dois mundos 💯 para notificações, chat e tal podemos usar _nosql_, e para informações gerencias o _sql_. O que acha @ayrtonteshima?

Sim, acho que podemos começar a pensar nessas questões! De qlqr forma a aplicação tem que ser desacoplada a quais bancos vamos usar e tal...

Quando pensei no modelo de o aluno assinar para ver todos os cursos, um modelo não relacional seria bom pois o curso teria suas disciplinas que tem suas aula e fim.

Agora se você pensa que pode vender curso por unidade, então uma disciplina poderia pertencer a outro curso, assim como as aulas... Aí já vejo um modelo relacional.

Acho que podemos fechar o escopo da issue #2 e definir o banco D

**Comment by walefe** [comment]
Poderíamos trabalhar a conteinerização da aplicação, ajudaria a entender melhor a questão dos ambientes de produção e desenvolvimento. Outro ponto legal também são os testes usando bibliotecas conhecidas como jest, mocha e chai. Na minha opinião são features importantes 👍

**Comment by ElvisDougJan** [comment]
Fala pessoal! Blz? Não sei se seria o mais correto abordar isso nessa issue, ou criar outra, mas e no que diz respeito a configuração do ambiente, vamos usar Eslint com algum padrão, como Standard, Airbnb, usar Prettier, vamos usar Babel? Coisas do gênero.

**Comment by ElvisDougJan** [comment]
E devido ao possível tamanho que o projeto pode tomar, usar Typescript não seria bom?

**Comment by ayrtonteshima** [comment]
> E devido ao possível tamanho que o projeto pode tomar, usar Typescript não seria bom?

Fala Elvis!
Não vejo necessidade... Vamos trabalhar com boas práticas e testes desde o início justamente por causa do tamanho dele.
Além disso está quebrado em 3 projetos, dividindo a complexidade :)

Porém, é uma discussão válida, caso tenham mais gente interessado podemos discutir isso! 
Abs

**Comment by ayrtonteshima** [comment]
> Poderíamos trabalhar a conteinerização da aplicação, ajudaria a entender melhor a questão dos ambientes de produção e desenvolvimento. Outro ponto legal também são os testes usando bibliotecas conhecidas como jest, mocha e chai. Na minha opinião são features importantes 👍

Vamos fazer tudo isso hehe
Por isso lancei duas aulas de Docker, vamos dockenizar tudo por ambiente ;)
Também vamos trabalhar com testes desde o início, vai ser um dos próximos vídeos!

**Comment by ayrtonteshima** [comment]
> Fala pessoal! Blz? Não sei se seria o mais correto abordar isso nessa issue, ou criar outra, mas e no que diz respeito a configuração do ambiente, vamos usar Eslint com algum padrão, como Standard, Airbnb, usar Prettier, vamos usar Babel? Coisas do gênero.

Já lancei o vídeo sobre o ESLint com config do airbnb hehe https://www.youtube.com/watch?v=wtjItQ_waeI

**Comment by pweslly** [comment]
Eu achando que seria Laravel com Vue.js e para mobile React Native. =)
